/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.Usuario;
import vista.GestionEquiposVista;
import vista.GestionTorneosVista;
import vista.GestionPartidosVista;
import vista.GestionPatrocinadoresVista;
import vista.LoginVista;
/**
 *
 * @author LENOVO
 */
public class MenuUsuario extends javax.swing.JFrame {
private Usuario usuario;
    /**
     * Creates new form MenuUsuario
     */
    public MenuUsuario(Usuario usuario) {

    initComponents();

    this.usuario = usuario;

    setLocationRelativeTo(null);

    lblNombre.setText(usuario.getNombre());
    lblRol.setText(usuario.getRol());

    configurarMenu();
}

    
    public void configurarMenu() {

    String rol = usuario.getRol();

    btnMiInformacion.setVisible(true);
    btnMiEquipo.setVisible(true);
    btnMisTorneos.setVisible(true);
    btnMisPartidos.setVisible(true);

    btnGestionEquipos.setVisible(false);
    btnGestionTorneos.setVisible(false);
    btnGestionPartidos.setVisible(false);
    btnGestionPatrocinadores.setVisible(false);
    btnReporte.setVisible(false);

    if (rol.equals("ORGANIZADOR")) {

        btnMiInformacion.setVisible(false);
        btnMiEquipo.setVisible(false);
        btnMisTorneos.setVisible(false);
        btnMisPartidos.setVisible(false);

        btnGestionEquipos.setVisible(true);
        btnGestionTorneos.setVisible(true);
        btnGestionPartidos.setVisible(true);
        btnGestionPatrocinadores.setVisible(true);
        btnReporte.setVisible(true);
    }

    if (rol.equals("ARBITRO")) {

        btnMiEquipo.setVisible(false);
        btnMisTorneos.setVisible(false);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMiInformacion = new javax.swing.JButton();
        btnMiEquipo = new javax.swing.JButton();
        btnMisTorneos = new javax.swing.JButton();
        btnMisPartidos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        btnGestionEquipos = new javax.swing.JButton();
        btnGestionTorneos = new javax.swing.JButton();
        btnGestionPartidos = new javax.swing.JButton();
        btnGestionPatrocinadores = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido:");

        jLabel2.setText("Rol:");

        btnMiInformacion.setText("Mi Informacion");
        btnMiInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiInformacionActionPerformed(evt);
            }
        });

        btnMiEquipo.setText("Mi Equipo");

        btnMisTorneos.setText("Mis Torneos");

        btnMisPartidos.setText("Mis Partidos");
        btnMisPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisPartidosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("MENU USUARIO");

        btnGestionEquipos.setText("Gestionar Equipos");
        btnGestionEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEquiposActionPerformed(evt);
            }
        });

        btnGestionTorneos.setText("Gestionar Torneos");
        btnGestionTorneos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionTorneosActionPerformed(evt);
            }
        });

        btnGestionPartidos.setText("Gestionar Partidos");
        btnGestionPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPartidosActionPerformed(evt);
            }
        });

        btnGestionPatrocinadores.setText("Gestionar Patrocinadores");
        btnGestionPatrocinadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPatrocinadoresActionPerformed(evt);
            }
        });

        jButton9.setForeground(new java.awt.Color(204, 0, 0));
        jButton9.setText("Cerrar Sesion");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnReporte.setText("Ver Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addComponent(lblRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnGestionPatrocinadores, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGestionEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnReporte))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnMiInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMiEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMisTorneos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMisPartidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGestionPartidos, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(btnGestionTorneos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblRol))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMiInformacion)
                    .addComponent(btnGestionEquipos)
                    .addComponent(btnGestionTorneos))
                .addGap(18, 18, 18)
                .addComponent(btnMiEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMisTorneos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMisPartidos)
                    .addComponent(btnGestionPartidos)
                    .addComponent(btnGestionPatrocinadores))
                .addGap(93, 93, 93)
                .addComponent(jButton9)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMiInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiInformacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMiInformacionActionPerformed

    private void btnMisPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisPartidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMisPartidosActionPerformed

    private void btnGestionEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEquiposActionPerformed
GestionEquiposVista vista = new GestionEquiposVista();

vista.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionEquiposActionPerformed

    private void btnGestionTorneosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionTorneosActionPerformed
GestionTorneosVista vista = new GestionTorneosVista();

vista.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionTorneosActionPerformed

    private void btnGestionPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPartidosActionPerformed
GestionPartidosVista vista = new GestionPartidosVista();

vista.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionPartidosActionPerformed

    private void btnGestionPatrocinadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPatrocinadoresActionPerformed
GestionPatrocinadoresVista vista = new GestionPatrocinadoresVista();

vista.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionPatrocinadoresActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
LoginVista login = new LoginVista();

login.setVisible(true);

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
   ReporteTorneosVista reporte = new ReporteTorneosVista();
reporte.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionEquipos;
    private javax.swing.JButton btnGestionPartidos;
    private javax.swing.JButton btnGestionPatrocinadores;
    private javax.swing.JButton btnGestionTorneos;
    private javax.swing.JButton btnMiEquipo;
    private javax.swing.JButton btnMiInformacion;
    private javax.swing.JButton btnMisPartidos;
    private javax.swing.JButton btnMisTorneos;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRol;
    // End of variables declaration//GEN-END:variables
}
